/*
 * generated by Xtext
 */
package eu.ascens.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {eu.ascens.validation.EnsembleStructureValidator.class, eu.ascens.validation.RoleBehaviorValidator.class, eu.ascens.validation.RoleTypeValidator.class, eu.ascens.validation.LogicValidator.class, eu.ascens.validation.ActionValidator.class})
public class AbstractHelenaTextValidator extends org.eclipse.xtext.xbase.validation.XbaseValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
	    result.add(eu.ascens.helenaText.HelenaTextPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/xbase/Xbase"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/common/JavaVMTypes"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/xbase/Xtype"));
		return result;
	}
}
