/*
 * generated by Xtext
 */
package eu.ascens.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.ascens.services.HelenaTextGrammarAccess;

public class HelenaTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HelenaTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.ascens.parser.antlr.internal.InternalHelenaTextParser createParser(XtextTokenStream stream) {
		return new eu.ascens.parser.antlr.internal.InternalHelenaTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public HelenaTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HelenaTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
