/*
 * generated by Xtext
 */
package eu.ascens.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.ascens.ui.internal.HelenaTextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HelenaTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HelenaTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HelenaTextActivator.getInstance().getInjector(HelenaTextActivator.EU_ASCENS_HELENATEXT);
	}
	
}
